[package]
name = "api-test-tauri"
version = "1.0.0"
edition = "2021"

[lib]
name = "api_test_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# Tauri
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"

# Async runtime
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tokio-tungstenite = "*"
futures = "0.3"
futures-util = "0.3.31"

# HTTP client
reqwest = { version = "0.12", features = ["json", "multipart"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
anyhow = "1"

# Utility
regex = "1"
lazy_static = "1.4"
rand = "0.8"
strum = { version = "0.24", features = ["derive"] }

# Script engine
rhai = { version = "1.19", features = ["sync", "serde"] }

# Crypto
md5 = "0.7"
sha2 = "0.10"
base64 = "0.22"
hex = "0.4"
hmac = "0.12"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
